name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * ?" # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: shahariarovi789-ux
          outputs: |
            github-user-contribution-grid-snake.svg
            github-user-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#8b5cf6&color_dots=#161b22,#3b0764,#581c87,#701a75,#a21caf,#d946ef

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-user-contribution-grid-snake.svg github-user-contribution-grid-snake-dark.svg
          git commit -m "chore: update contribution snake animation with custom purple palette" || exit 0
          git push
